# (C) Copyright Confidential Containers Contributors
# # SPDX-License-Identifier: Apache-2.0
#
# Build binary and run unit tests
---
name: build

on:
  pull_request:
  workflow_dispatch:

jobs:

  controllers:
    name: controllers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        controller:
          - peerpodconfig-ctrl
    defaults:
      run:
        working-directory: ${{ matrix.controller }}
    steps:
      - name: Checkout the pull request code
        uses: actions/checkout@v4

      - name: Read properties from versions.yaml
        run: |
          go_version="$(yq '.tools.golang' ../versions.yaml)"
          [ -n "$go_version" ]
          echo "GO_VERSION=${go_version}" >> "$GITHUB_ENV"

      - name: Setup Golang version ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install build dependencies
        if: matrix.controller == 'peerpod-ctrl'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvirt-dev

      - name: Verify go modules and manifests
        run: make verify

      - name: Build the controller manager
        run: make build

      - name: Run unit tests
        run: make test

      - name: Build the controller image
        run: make docker-build
